-- cpu_signal_wait.sql : high signal_wait% => threads ready but waiting for CPU
SELECT
    SUM(signal_wait_time_ms) * 100.0 / NULLIF(SUM(wait_time_ms),0) AS signal_wait_pct,
    SUM(wait_time_ms) AS total_wait_ms
FROM sys.dm_os_wait_stats
WHERE wait_type NOT IN (  -- benign/idle waits excluded
    'CLR_SEMAPHORE','LAZYWRITER_SLEEP','RESOURCE_QUEUE','SLEEP_TASK','SLEEP_SYSTEMTASK',
    'SQLTRACE_BUFFER_FLUSH','WAITFOR','LOGMGR_QUEUE','CHECKPOINT_QUEUE','REQUEST_FOR_DEADLOCK_SEARCH',
    'XE_TIMER_EVENT','BROKER_TO_FLUSH','BROKER_TASK_STOP','CLR_MANUAL_EVENT','CLR_AUTO_EVENT',
    'DISPATCHER_QUEUE_SEMAPHORE','FT_IFTS_SCHEDULER_IDLE_WAIT','XE_DISPATCHER_WAIT','XE_DISPATCHER_JOIN',
    'BROKER_EVENTHANDLER','TRACEWRITE','FT_IFTSHC_MUTEX','SQLTRACE_INCREMENTAL_FLUSH_SLEEP',
    'DIRTY_PAGE_POLL','SP_SERVER_DIAGNOSTICS_SLEEP','HADR_FILESTREAM_IOMGR_IOCOMPLETION',
    'ONDEMAND_TASK_QUEUE','BROKER_RECEIVE_WAITFOR','PWAIT_ALL_COMPONENTS_INITIALIZED');
